#!/bin/bash
# point this at the IP address of your OpenWRT build box
# assumes you have set up root ssh access

MyOpenWRT=9.180.88.55

echo -e "Copy over some files"
rm -rf dist*
mkdir -p dist
scp -p *.sh root@$MyOpenWRT:
scp -pr *luci* root@$MyOpenWRT:/etc/node-red/
scp -p flows*.json root@$MyOpenWRT:/etc/node-red/
scp -p node-red root@$MyOpenWRT:/etc/init.d/node-red
ssh root@$MyOpenWRT rm -f /etc/node-red/.*.backup
ssh root@$MyOpenWRT ./ipk-pack.sh
cd dist
scp -p root@$MyOpenWRT:/tmp/node*.ipk ./
../opkg-utils/opkg-make-index . > Packages
gzip Packages
cd ..
ls -l dist/*
echo -e "\nAll Done."
